apiVersion: v1
kind: Service
metadata:
  name: jyewordpressweb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: jyewordpressweb
